### ISSUE TITLE
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

### ISSUE THREAD

**Issue by zhangxii** [FlagOpen/TACO#3]
When I use `compute_metric.py` to evaluate the generation results, the console noted "no module named `pyext`." I installed it using pip and got the following error:
```
Collecting pyext
  Using cached pyext-0.7.tar.gz (7.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "...\AppData\Local\Temp\pip-install-exx9gznl\pyext_28002897deae467da164cbba24ad8613\setup.py", line 6, in <module>
          import pyext
        File "...\AppData\Local\Temp\pip-install-exx9gznl\pyext_28002897deae467da164cbba24ad8613\pyext.py", line 117, in <module>
          oargspec = inspect.getargspec
                     ^^^^^^^^^^^^^^^^^^
      AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

After searching online, I found out that this is a Python bug and I'm using Python 3.11 to support OpenAI's models.

Upon further investigation, it appears that this issue doesn't exist in Python 3.8, so I downgraded the Python version to 3.8.

Moreover, Someone mentioned that the problem may be resolved in the second quarter of 2024: https://community.privacyidea.org/t/python-3-11-support/3115/2

I suggest providing some detailed environment setting on the guide page.

**Comment by rongaoli** [comment]
OK, thanks for your advice!
